### ISSUE TITLE
Power Button Does Not Turn On Xiaomi TV

### ISSUE THREAD

**Issue by juan11perez** [shammysha/esphome-ble-mi-remote#2]
First, thank  you for putting this together. Much appreciated.
I created one 'remote' and added it to mi xiaomi tv [Xiaomi Mi 43 Inch UHD Smart android TV-L43M5-5ASP](https://mi-home.pl/en/products/mi-led-tv-4s-43).

With the TV on I believe all buttons work as intended. When I press the power button it turns off the tv; but If I press it while the tv is off, then it does nothing.

Waking these tv's wirelessly is a sought after solution in the hass  [forums](https://community.home-assistant.io/t/manage-xiaomi-mitv-emulating-the-remote-control-as-it-is-an-android-bluetooth-device/285705/20).

I wander if  you could perhaps consider taking a look at the power button to trigger the tv turning on.

Thank you.

**Comment by juan11perez** [comment]
Never mind, it works perfect. 
Thank you very much

**Comment by Mikhail-Semerkov** [comment]
Hi, what was done to turn on the TV? I also can't turn it on!

**Comment by juan11perez** [comment]
Apologies, 
It doesnt turn the tv on if the tv is turned off.

**Comment by Boldfor** [comment]
If I read the HomeAssistant Thread correctly, this repo should do the trick: https://github.com/frlequ/mibox_socket

Anyone tried it? Problem: It does not work on ESPs but requires a Raspi. In general not a problem,  it not a super nice solution…

**Comment by Boldfor** [comment]
If I read the HomeAssistant Thread correctly, this repo should do the trick: https://github.com/frlequ/mibox_socket

Anyone tried it? Problem: It does not work on ESPs but requires a Raspi. In general not a problem,  it not a super nice solution…
